-- 2026-10-02 批次把「壓克力途程 × 印刷站/雷切站」的 qty_mode 改成「盤數」的回復腳本。
--
-- 依據：生管確認「所有壓克力的印刷與雷切都要用盤數計算工時，4mm 以上也一樣」。
-- 原本這些工序停在欄位預設值「個數」（qty_mode 的 DEFAULT），是 2026-08-24 建欄位後
-- 一直沒補完的設定，不是刻意選的——同品類的 2mm 全是盤數，只有 3mm 與 4mm 以上停在預設。
--
-- 要全部回復成改動前的值，執行以下 update。

update public.route_operations set qty_mode = '個數' where id = 4414;  -- 軟墨單面印刷/壓克力 / 軟墨壓克力UV印刷
update public.route_operations set qty_mode = '個數' where id = 4415;  -- 軟墨單面印刷/壓克力 / 雷射切割-3mm板材/畫板
update public.route_operations set qty_mode = '個數' where id = 4505;  -- 3mm壓克力畫板/單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4506;  -- 3mm壓克力畫板/單面印刷 / 雷射切割-3mm板材/畫板
update public.route_operations set qty_mode = '個數' where id = 4508;  -- 3mm壓克力畫板/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4509;  -- 3mm壓克力畫板/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4510;  -- 3mm壓克力畫板/雙面印刷 / 雷射切割-3mm板材/畫板
update public.route_operations set qty_mode = '個數' where id = 4512;  -- 3mm壓克力畫板/V90單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4513;  -- 3mm壓克力畫板/V90單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4514;  -- 3mm壓克力畫板/V90單面印刷 / 雷射切割-3mm板材/畫板
update public.route_operations set qty_mode = '個數' where id = 4516;  -- 3mm壓克力畫板/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4517;  -- 3mm壓克力畫板/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4518;  -- 3mm壓克力畫板/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4519;  -- 3mm壓克力畫板/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4520;  -- 3mm壓克力畫板/V90雙面印刷 / 雷射切割-3mm板材/畫板
update public.route_operations set qty_mode = '個數' where id = 4522;  -- 3mm壓克力片/單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4523;  -- 3mm壓克力片/單面印刷 / 雷射切割-3mm板材/立牌
update public.route_operations set qty_mode = '個數' where id = 4525;  -- 3mm壓克力片/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4526;  -- 3mm壓克力片/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4527;  -- 3mm壓克力片/雙面印刷 / 雷射切割-3mm板材/立牌
update public.route_operations set qty_mode = '個數' where id = 4529;  -- 3mm壓克力片/V90單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4530;  -- 3mm壓克力片/V90單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4531;  -- 3mm壓克力片/V90單面印刷 / 雷射切割-3mm板材/立牌
update public.route_operations set qty_mode = '個數' where id = 4533;  -- 3mm壓克力片/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4534;  -- 3mm壓克力片/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4535;  -- 3mm壓克力片/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4536;  -- 3mm壓克力片/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4537;  -- 3mm壓克力片/V90雙面印刷 / 雷射切割-3mm板材/立牌
update public.route_operations set qty_mode = '個數' where id = 4539;  -- 3mm壓克力鑰匙圈/單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4540;  -- 3mm壓克力鑰匙圈/單面印刷 / 雷射切割-3mm板材/鑰匙圈
update public.route_operations set qty_mode = '個數' where id = 4542;  -- 3mm壓克力鑰匙圈/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4543;  -- 3mm壓克力鑰匙圈/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4544;  -- 3mm壓克力鑰匙圈/雙面印刷 / 雷射切割-3mm板材/鑰匙圈
update public.route_operations set qty_mode = '個數' where id = 4546;  -- 3mm壓克力鑰匙圈/V90單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4547;  -- 3mm壓克力鑰匙圈/V90單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4548;  -- 3mm壓克力鑰匙圈/V90單面印刷 / 雷射切割-3mm板材/鑰匙圈
update public.route_operations set qty_mode = '個數' where id = 4550;  -- 3mm壓克力鑰匙圈/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4551;  -- 3mm壓克力鑰匙圈/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4552;  -- 3mm壓克力鑰匙圈/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4553;  -- 3mm壓克力鑰匙圈/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4554;  -- 3mm壓克力鑰匙圈/V90雙面印刷 / 雷射切割-3mm板材/鑰匙圈
update public.route_operations set qty_mode = '個數' where id = 4573;  -- 3mm壓克力串3串鑰匙圈/單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4574;  -- 3mm壓克力串3串鑰匙圈/單面印刷 / 雷射切割-3mm板材/鑰匙圈
update public.route_operations set qty_mode = '個數' where id = 4576;  -- 3mm壓克力串3串鑰匙圈/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4577;  -- 3mm壓克力串3串鑰匙圈/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4578;  -- 3mm壓克力串3串鑰匙圈/雙面印刷 / 雷射切割-3mm板材/鑰匙圈
update public.route_operations set qty_mode = '個數' where id = 4581;  -- 3mm壓克力串3串鑰匙圈/V90單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4582;  -- 3mm壓克力串3串鑰匙圈/V90單面印刷 / 雷射切割-3mm板材/鑰匙圈
update public.route_operations set qty_mode = '個數' where id = 4584;  -- 3mm壓克力串3串鑰匙圈/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4585;  -- 3mm壓克力串3串鑰匙圈/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4586;  -- 3mm壓克力串3串鑰匙圈/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4587;  -- 3mm壓克力串3串鑰匙圈/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4588;  -- 3mm壓克力串3串鑰匙圈/V90雙面印刷 / 雷射切割-3mm板材/鑰匙圈
update public.route_operations set qty_mode = '個數' where id = 4590;  -- 8mm壓克力鑰匙圈/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4591;  -- 8mm壓克力鑰匙圈/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4592;  -- 8mm壓克力鑰匙圈/雙面印刷 / 雷射切割-3mm板材/鑰匙圈
update public.route_operations set qty_mode = '個數' where id = 4594;  -- 3mm壓克力立牌/單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4595;  -- 3mm壓克力立牌/單面印刷 / 雷射切割-3mm板材/立牌
update public.route_operations set qty_mode = '個數' where id = 4597;  -- 3mm壓克力立牌/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4598;  -- 3mm壓克力立牌/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4599;  -- 3mm壓克力立牌/雙面印刷 / 雷射切割-3mm板材/立牌
update public.route_operations set qty_mode = '個數' where id = 4601;  -- 3mm壓克力立牌/V90單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4602;  -- 3mm壓克力立牌/V90單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4603;  -- 3mm壓克力立牌/V90單面印刷 / 雷射切割-3mm板材/立牌
update public.route_operations set qty_mode = '個數' where id = 4605;  -- 3mm壓克力立牌/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4606;  -- 3mm壓克力立牌/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4607;  -- 3mm壓克力立牌/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4608;  -- 3mm壓克力立牌/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4609;  -- 3mm壓克力立牌/V90雙面印刷 / 雷射切割-3mm板材/立牌
update public.route_operations set qty_mode = '個數' where id = 4611;  -- 3mm壓克力立牌(組合)/單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4612;  -- 3mm壓克力立牌(組合)/單面印刷 / 雷射切割-3mm板材/立牌
update public.route_operations set qty_mode = '個數' where id = 4614;  -- 3mm壓克力立牌(組合)/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4615;  -- 3mm壓克力立牌(組合)/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4616;  -- 3mm壓克力立牌(組合)/雙面印刷 / 雷射切割-3mm板材/立牌
update public.route_operations set qty_mode = '個數' where id = 4618;  -- 3mm壓克力立牌(組合)/V90單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4619;  -- 3mm壓克力立牌(組合)/V90單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4620;  -- 3mm壓克力立牌(組合)/V90單面印刷 / 雷射切割-3mm板材/立牌
update public.route_operations set qty_mode = '個數' where id = 4622;  -- 3mm壓克力立牌(組合)/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4623;  -- 3mm壓克力立牌(組合)/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4624;  -- 3mm壓克力立牌(組合)/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4625;  -- 3mm壓克力立牌(組合)/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4626;  -- 3mm壓克力立牌(組合)/V90雙面印刷 / 雷射切割-3mm板材/立牌
update public.route_operations set qty_mode = '個數' where id = 4628;  -- 3mm壓克力拼板立牌/單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4629;  -- 3mm壓克力拼板立牌/單面印刷 / 雷射切割-3mm板材/拼板立牌
update public.route_operations set qty_mode = '個數' where id = 4631;  -- 3mm壓克力拼板立牌/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4632;  -- 3mm壓克力拼板立牌/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4633;  -- 3mm壓克力拼板立牌/雙面印刷 / 雷射切割-3mm板材/拼板立牌
update public.route_operations set qty_mode = '個數' where id = 4635;  -- 3mm壓克力拼板立牌/V90單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4636;  -- 3mm壓克力拼板立牌/V90單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4637;  -- 3mm壓克力拼板立牌/V90單面印刷 / 雷射切割-3mm板材/拼板立牌
update public.route_operations set qty_mode = '個數' where id = 4639;  -- 3mm壓克力拼板立牌/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4640;  -- 3mm壓克力拼板立牌/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4641;  -- 3mm壓克力拼板立牌/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4642;  -- 3mm壓克力拼板立牌/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4643;  -- 3mm壓克力拼板立牌/V90雙面印刷 / 雷射切割-3mm板材/拼板立牌
update public.route_operations set qty_mode = '個數' where id = 4645;  -- 3mm壓克力手機氣囊支架/單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4802;  -- 4mm造型壓克力/V90單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4646;  -- 3mm壓克力手機氣囊支架/單面印刷 / 雷射切割-3mm板材/鑰匙圈
update public.route_operations set qty_mode = '個數' where id = 4649;  -- 3mm壓克力手機氣囊支架/V90單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4650;  -- 3mm壓克力手機氣囊支架/V90單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4651;  -- 3mm壓克力手機氣囊支架/V90單面印刷 / 雷射切割-3mm板材/鑰匙圈
update public.route_operations set qty_mode = '個數' where id = 4654;  -- 3mm滴膠鑰匙圈壓克力/單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4655;  -- 3mm滴膠鑰匙圈壓克力/單面印刷 / 雷射切割-3mm板材/鑰匙圈
update public.route_operations set qty_mode = '個數' where id = 4658;  -- 3mm滴膠鑰匙圈壓克力/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4659;  -- 3mm滴膠鑰匙圈壓克力/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4660;  -- 3mm滴膠鑰匙圈壓克力/雙面印刷 / 雷射切割-3mm板材/鑰匙圈
update public.route_operations set qty_mode = '個數' where id = 4663;  -- 3mm滴膠壓克力磁鐵/單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4664;  -- 3mm滴膠壓克力磁鐵/單面印刷 / 雷射切割-3mm板材/鑰匙圈
update public.route_operations set qty_mode = '個數' where id = 4667;  -- 3mm滴膠壓克力磁鐵/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4668;  -- 3mm滴膠壓克力磁鐵/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4669;  -- 3mm滴膠壓克力磁鐵/雙面印刷 / 雷射切割-3mm板材/鑰匙圈
update public.route_operations set qty_mode = '個數' where id = 4672;  -- 3mm滴膠壓克力氣囊支架/單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4673;  -- 3mm滴膠壓克力氣囊支架/單面印刷 / 雷射切割-3mm板材/鑰匙圈
update public.route_operations set qty_mode = '個數' where id = 4676;  -- 3mm滴膠壓克力氣囊支架/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4677;  -- 3mm滴膠壓克力氣囊支架/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4678;  -- 3mm滴膠壓克力氣囊支架/雙面印刷 / 雷射切割-3mm板材/鑰匙圈
update public.route_operations set qty_mode = '個數' where id = 4681;  -- 3mm壓克力磁鐵/單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4683;  -- 3mm壓克力磁鐵/單面印刷 / 雷射切割-3mm板材/鑰匙圈
update public.route_operations set qty_mode = '個數' where id = 4702;  -- 6mm+2mm壓克力貼合/單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4704;  -- 6mm+2mm壓克力貼合/單面印刷 / 雷射切割-8mm板材
update public.route_operations set qty_mode = '個數' where id = 4706;  -- 8mm+2mm壓克力貼合/單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4708;  -- 8mm+2mm壓克力貼合/單面印刷 / 雷射切割-10mm板材
update public.route_operations set qty_mode = '個數' where id = 4725;  -- 6mm+2mm壓克力貼合/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4726;  -- 6mm+2mm壓克力貼合/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4728;  -- 6mm+2mm壓克力貼合/雙面印刷 / 雷射切割-8mm板材
update public.route_operations set qty_mode = '個數' where id = 4730;  -- 8mm+2mm壓克力貼合/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4731;  -- 8mm+2mm壓克力貼合/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4733;  -- 8mm+2mm壓克力貼合/雙面印刷 / 雷射切割-10mm板材
update public.route_operations set qty_mode = '個數' where id = 4747;  -- 6mm+2mm壓克力貼合/V90單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4749;  -- 6mm+2mm壓克力貼合/V90單面印刷 / 雷射切割-8mm板材
update public.route_operations set qty_mode = '個數' where id = 4751;  -- 8mm+2mm壓克力貼合/V90單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4753;  -- 8mm+2mm壓克力貼合/V90單面印刷 / 雷射切割-10mm板材
update public.route_operations set qty_mode = '個數' where id = 4775;  -- 6mm+2mm壓克力貼合/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4776;  -- 6mm+2mm壓克力貼合/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4778;  -- 6mm+2mm壓克力貼合/V90雙面印刷 / 雷射切割-8mm板材
update public.route_operations set qty_mode = '個數' where id = 4780;  -- 8mm+2mm壓克力貼合/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4781;  -- 8mm+2mm壓克力貼合/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4783;  -- 8mm+2mm壓克力貼合/V90雙面印刷 / 雷射切割-10mm板材
update public.route_operations set qty_mode = '個數' where id = 4795;  -- 4mm造型壓克力/單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4796;  -- 4mm造型壓克力/單面印刷 / 雷射切割-4mm板材/鑰匙圈
update public.route_operations set qty_mode = '個數' where id = 4798;  -- 4mm造型壓克力/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4799;  -- 4mm造型壓克力/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4800;  -- 4mm造型壓克力/雙面印刷 / 雷射切割-4mm板材/鑰匙圈
update public.route_operations set qty_mode = '個數' where id = 4803;  -- 4mm造型壓克力/V90單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4804;  -- 4mm造型壓克力/V90單面印刷 / 雷射切割-4mm板材/鑰匙圈
update public.route_operations set qty_mode = '個數' where id = 4806;  -- 4mm造型壓克力/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4807;  -- 4mm造型壓克力/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4808;  -- 4mm造型壓克力/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4809;  -- 4mm造型壓克力/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4810;  -- 4mm造型壓克力/V90雙面印刷 / 雷射切割-4mm板材/鑰匙圈
update public.route_operations set qty_mode = '個數' where id = 4812;  -- 5mm造型壓克力/單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4813;  -- 5mm造型壓克力/單面印刷 / 雷射切割-5mm板材
update public.route_operations set qty_mode = '個數' where id = 4815;  -- 5mm造型壓克力/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4816;  -- 5mm造型壓克力/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4817;  -- 5mm造型壓克力/雙面印刷 / 雷射切割-5mm板材
update public.route_operations set qty_mode = '個數' where id = 4819;  -- 5mm造型壓克力/V90單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4820;  -- 5mm造型壓克力/V90單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4821;  -- 5mm造型壓克力/V90單面印刷 / 雷射切割-5mm板材
update public.route_operations set qty_mode = '個數' where id = 4823;  -- 5mm造型壓克力/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4824;  -- 5mm造型壓克力/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4825;  -- 5mm造型壓克力/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4826;  -- 5mm造型壓克力/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4827;  -- 5mm造型壓克力/V90雙面印刷 / 雷射切割-5mm板材
update public.route_operations set qty_mode = '個數' where id = 4829;  -- 5mm造型壓克力/雷射雕刻 / 雷射切割-5mm板材
update public.route_operations set qty_mode = '個數' where id = 4830;  -- 5mm造型壓克力/雷射雕刻 / 雷射雕刻
update public.route_operations set qty_mode = '個數' where id = 4832;  -- 6mm造型壓克力/單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4833;  -- 6mm造型壓克力/單面印刷 / 雷射切割-6mm板材
update public.route_operations set qty_mode = '個數' where id = 4835;  -- 6mm造型壓克力/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4836;  -- 6mm造型壓克力/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4837;  -- 6mm造型壓克力/雙面印刷 / 雷射切割-6mm板材
update public.route_operations set qty_mode = '個數' where id = 4839;  -- 6mm造型壓克力/V90單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4840;  -- 6mm造型壓克力/V90單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4841;  -- 6mm造型壓克力/V90單面印刷 / 雷射切割-6mm板材
update public.route_operations set qty_mode = '個數' where id = 4843;  -- 6mm造型壓克力/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4844;  -- 6mm造型壓克力/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4845;  -- 6mm造型壓克力/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4846;  -- 6mm造型壓克力/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4847;  -- 6mm造型壓克力/V90雙面印刷 / 雷射切割-6mm板材
update public.route_operations set qty_mode = '個數' where id = 4849;  -- 8mm造型壓克力/單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4850;  -- 8mm造型壓克力/單面印刷 / 雷射切割-8mm板材
update public.route_operations set qty_mode = '個數' where id = 4852;  -- 8mm造型壓克力/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4853;  -- 8mm造型壓克力/雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4854;  -- 8mm造型壓克力/雙面印刷 / 雷射切割-8mm板材
update public.route_operations set qty_mode = '個數' where id = 4856;  -- 8mm造型壓克力/V90單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4857;  -- 8mm造型壓克力/V90單面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4858;  -- 8mm造型壓克力/V90單面印刷 / 雷射切割-8mm板材
update public.route_operations set qty_mode = '個數' where id = 4860;  -- 8mm造型壓克力/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4861;  -- 8mm造型壓克力/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4862;  -- 8mm造型壓克力/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4863;  -- 8mm造型壓克力/V90雙面印刷 / UV印刷
update public.route_operations set qty_mode = '個數' where id = 4864;  -- 8mm造型壓克力/V90雙面印刷 / 雷射切割-8mm板材
